### PR TITLE
News entry on Orthtree

### PR DESCRIPTION
**Pull request by JacksonCampolattaro**
First version of a news entry on the new Orthtree package.

### To Do
- [ ] Link targets for Cédric Portaneri and Tong Zhao's names.
- [ ] Links for any other organizations involved.
- [ ] Expected release date of CGAL 5.3

### CODE REVIEW

**Comment by lrineau** [comment]
It looks good here:
https://upcoming.cgal.org/2021/04/27/Orthtree/

But the "CGAL" at the end looks strange. Could you chose a longer heading title?
Screenshot_20210428_090504

**Comment by sgiraudot** [comment]
@lrineau I replaced by "'Status and links"

**Comment by lrineau** [comment]
https://github.com/CGAL/cgal-web/blob/770175fd7eb1856b562a268cf447b1ead5dd9776/_posts/2021-04-27-Orthtree.md#L11-L15

As for the URLs for Cédric and Tong it could be Linkedin addresses:
  - https://www.linkedin.com/in/cédric-portaneri-1516a1108/
  - https://www.linkedin.com/in/tong-zhao-8613a8116/

**Comment by sgiraudot** [comment]
Oops, sorry about that, I fixed it.

**Comment by MaelRL** [comment]
` description: "New Orthtree data structure for ..."` is incomplete.

**Pull request merged**
