### PR TITLE
Add post for Surface mesh topology

### PR DESCRIPTION
**Pull request by gdamiand**
Add a post in the news for the new packake Surface mesh topology.

Untested, I don't know how to view the updated web site, sorry.

### CODE REVIEW

**Comment by MaelRL** [comment]
Thanks!

You can test locally with `jekyll serve --watch`, or merge into the "upcoming" branch and then look at [upcoming.cgal.org](https://upcoming.cgal.org/). [Here](https://upcoming.cgal.org/2020/04/30/Surface_mesh_topology/) it is on the preview.

**Comment by gdamiand** [comment]
Thanks Mael !

**Comment by sloriot** [comment]
Can you produce a picture from a more complicated object/real object? It would look more appealing.

**Comment by gdamiand** [comment]
> Can you produce a picture from a more complicated object/real object? It would look more appealing.

Done, cf https://upcoming.cgal.org/2020/04/30/Surface_mesh_topology/.

**Comment by MaelRL** [comment]
@gdamiand May I please edit directly within the branch for a few rephrases / formatting issues?

**Comment by gdamiand** [comment]
> @gdamiand May I please edit directly within the branch for a few rephrases / formatting issues?

Yes of course, thanks !

**Comment by gdamiand** [comment]
Am I supposed to merge myself this branch in master ?

**Comment by sloriot** [comment]
As soon as you're happy with it :)

**Comment by MaelRL** [comment]
I intend to do a few modifications and once you've validated these changes, you can merge it.

**Comment by gdamiand** [comment]
Ok, thanks @MaelRL  and @sloriot .

**Pull request merged**
